version: "3"

services:
  jenkins:
    image: moso/jenkins
    build: ./jenkins
    ports:
      - "58080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  docker-registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  jenkins_data:
  registry_data:
